# Generated by Django 2.1.11 on 2020-07-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(default='BJxVzKcADPzOlLKMNBIQctPLWmkLzDbNhjTvJFaq', max_length=40),
        ),
    ]
