# Generated by Django 2.1.11 on 2020-08-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200801_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(default='mITgpRNhYDhjoFrSnLgvJtyNrKKlSTxoOALsTASu', max_length=40),
        ),
    ]
