# Generated by Django 3.0.8 on 2020-08-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200801_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=30, verbose_name='Название сайта')),
                ('description', models.TextField(max_length=200, verbose_name='Описание сайта')),
                ('footer', models.CharField(max_length=255, verbose_name='Футр')),
                ('token', models.CharField(max_length=255, verbose_name='Qiwi token')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер Qiwi')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(default='aGBNgVTOubkUCrsQWkTgxKrijGmWFttcebsfhMED', max_length=40),
        ),
    ]
